### ISSUE TITLE
a suggestion to increase the update speed 

### ISSUE THREAD

**Issue by betayi** [tonymmm1/vmangos-docker#14]
every time the vmangos/core/ was updated, the way i wanna keep it's step is rebuild the  build container, that will remove the old build image,  and rebuild from the ubuntu image without all utils that updated at first time, then copy the src code at host volume to compile directory  before it start the compile work, 

and then comes with a question, it takes a very very long time to get ready for the compile enviroments , cause the utils repo source server or mirror's server don't have a nice download speed at most of the time, after that ,the compiling takes few minutes 

so ,can suggestion below this should be help for question above? 

make the build container's compile directory with src code as a host volume ?
 with --update parameter, the script can up the build container  but not rebuild the whole image ?

thx

**Comment by tonymmm1** [comment]
What you can do to cache is setup apt-cacher-ng and edit the Dockerfile to make sure that the container pulls from your local cache. In the first line of the Dockerfiles by issuing a command to point to cache server. The apt-get update step is intentional to make sure that all the dependencies are installed and or update to the latest available. However I am running docker-compose build so it will use existing layers if not necessary to update and therefore should already be cached.

**Comment by betayi** [comment]
emm，maybe i got the wrong way to keep compiling the recently core code with shell "basic_setup.sh", 
but it won't compile the new cpp indeed, maybe the cpp code was copied as part of image and be cached ?

after splite the source code as a new image based on the updated os layer image, 
it makes the whole rebuild time reduce to 1-2 min from 30-60 min,  
cuz the updated os layer image was cached , it needn't be as recently as the core code we need, right ?

**Comment by tonymmm1** [comment]
Try using the python setup.py script instead. I only intended for the basic_setup.sh to be used for initial install. Run the command

To explain the command you can read the README.md

```
-m1 is no web
--update is update command
-t is the number of threads
```

```
./setup.py -m1 --update -t4
```

**Comment by betayi** [comment]
thanks a lot, there are so many diffrent between the python scripts and the shell scripts , for some unknnown reasons, python 3.5.5 don't work well on my host, so ,i choosed shell scripts, just like a  lite version without lot of function . anyway, we know what the question is, and how we can resolve it , it's still a nice project that i ever looked after ,thank u for all of this !
