### ISSUE TITLE
merge.sh

### ISSUE THREAD

**Issue by ghost** [tonymmm1/vmangos-docker#8]
i think i found something in setup.py because im getting errors there.
```
#Merging all sql migrations
    os.chdir("src/core/sql/migrations")                     #cd /src/core/sql/migrations
    subprocess.run(["chmod","+x","merge.sh"],check=True)    #chmod +x merge.sh
    subprocess.run(["./merge.sh"],check=True)               #./merge.sh
    os.chdir(path)                                          #cd path 
```
there is no merge.sh in src/core/sql and subprocess.run(["./merge.sh"],check=True)    will retunr errors

**Comment by tonymmm1** [comment]
May I see the error output so I can tell if its a python error or an os one.

**Comment by ghost** [comment]
```
Beginning setup
Traceback (most recent call last):
  File "setup.py", line 346, in <module>
    setup()
  File "setup.py", line 236, in setup
    subprocess.run(["./merge.sh"],check=True)               #./merge.sh
  File "C:\Users\Patyk\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Patyk\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Patyk\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 nie jest prawidłową aplikacją systemu Win32
```

**Comment by ghost** [comment]
dont know if im doing all wrong. Im on windows 10 pro with installed docker. To run all other subprocess methods correclty i start setup.py in cygwin.
1. create project from git repository,
2. update to fetch all sub repositories with vmangos and fusiongen
3. run ```chmod+x setup.py``` in cygwin (nothing happens)
4. then i run ```python setup.py``` command.
5. now it runs correctly asking configuration questions
6. returns error

**Comment by ghost** [comment]
ok, my bad i didnt know to run shell scripts is used ``` ./```
but still doesnt work in windows using cygwin or wsl

**Comment by tonymmm1** [comment]
Yeah this script is primarily setup for Unix systems so I do not promise that Cygwin will work maybe something like [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) might work. Also you must have python 3.5+ otherwise subprocess.run will fail. Also are you not running 64 bit Windows this will definitely not work with 32 bit Windows or Python.
